export const data = [
  {
    nombres: "Luisa",
    apellidos: "Morales",
    edad: 18,
    correo: "luisamoralesocp@gmail.com",
    cargo: "Desarrolladora",
    salario: 4000000,
  },
  {
    nombres: "Dana",
    apellidos: "Carrillo",
    edad: 17,
    correo: "danacarrillo@gmail.com",
    cargo: "Desarrolladora",
    salario: 4000000,
  },
  {
    nombres: "Nathalie",
    apellidos: "Pareja",
    edad: 18,
    correo: "natypale@gmail.com",
    cargo: "Desarrolladora",
    salario: 4000000,
  },
  {
    nombres: "Michelle",
    apellidos: "Parra",
    edad: 18,
    correo: "michelleparra@gmail.com",
    cargo: "Desarrolladora",
    salario: 4000000,
  },
  {
    nombres: "Sebastián",
    apellidos: "Monsalve",
    edad: 17,
    correo: "sebastianmonsalve@gmail.com",
    cargo: "Desarrollador",
    salario: 4000000,
  },
  {
    nombres: "Sebastián",
    apellidos: "Lopéz",
    edad: 17,
    correo: "sebaslopez@gmail.com",
    cargo: "Desarrollador",
    salario: 4000000,
  },
  {
    nombres: "Sebastián",
    apellidos: "Morales",
    edad: 4,
    correo: "sebasmorales@gmail.com",
    cargo: "Joder la vida",
    salario: 100,
  },
  {
    nombres: "Alejandro",
    apellidos: "Meza",
    edad: 21,
    correo: "alejandromeza@gmail.com",
    cargo: "Desarrollador",
    salario: 4000000,
  },
  {
    nombres: "Salomé",
    apellidos: "Betancur",
    edad: 17,
    correo: "salomebetancurgmail.com",
    cargo: "Ingeniera Ambiental",
    salario: 4000000,
  },
  {
    nombres: "Emely",
    apellidos: "Meza",
    edad: 17,
    correo: "emelymeza@gmail.com",
    cargo: "Cirujana",
    salario: 4000000,
  },
  {
    nombres: "Santiago",
    apellidos: "Parra",
    edad: 20,
    correo: "santiagoparra@gmail.com",
    cargo: "Desarrollador",
    salario: 4000000,
  },
  {
    nombres: "Sara",
    apellidos: "Pareja",
    edad: 22,
    correo: "sarapareja@gmail.com",
    cargo: "Administradora de empresas",
    salario: 4000000,
  },
  {
    nombres: "Diana",
    apellidos: "Ocampo",
    edad: 48,
    correo: "dianaocampo@gmail.com",
    cargo: "Manicurista",
    salario: 4000000,
  },
  {
    nombres: "Elgidio",
    apellidos: "Morales",
    edad: 50,
    correo: "elgidiomorales@gmail.com",
    cargo: "Conductor",
    salario: 4000000,
  },
  {
    nombres: "Manuela",
    apellidos: "Gómez",
    edad: 18,
    correo: "manugomez@gmail.com",
    cargo: "Psicologa",
    salario: 4000000,
  },
  {
    nombres: "Camilo",
    apellidos: "Acevedo",
    edad: 25,
    correo: "camiloacevedo@gmail.com",
    cargo: "Historiador",
    salario: 4000000,
  },
  {
    nombres: "Juan",
    apellidos: "Acevedo",
    edad: 18,
    correo: "juanacevedo@gmail.com",
    cargo: "Veterinario",
    salario: 4000000,
  },
  {
    nombres: "Cristian",
    apellidos: "Berrio",
    edad: 25,
    correo: "cristianberrio@gmail.com",
    cargo: "Electricista",
    salario: 4000000,
  },
  {
    nombres: "Rosa",
    apellidos: "Berrio",
    edad: 58,
    correo: "rosaberrio@gmail.com",
    cargo: "Ama de casa",
    salario: 4000000,
  },
  {
    nombres: "Eroelia",
    apellidos: "Morales",
    edad: 58,
    correo: "eroeliamorales@gmail.com",
    cargo: "Ama de casa",
    salario: 4000000,
  },
];

